export const LOAD_AUTHORS_START = "LOAD_AUTHORS_START";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const UPDATE_AUTHOR_RATING = "UPDATE_AUTHOR_RATING";

export const LOAD_PHOTOS_START = "LOAD_PHOTOS_START";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const UPDATE_PHOTO_LIKES = "UPDATE_PHOTO_LIKES";

export const TOGGLE_PHOTO = "TOGGLE_PHOTO";
